#!/bin/bash

# https://github.com/veleire/youtube-dl-mp3-bash
# simple bash script to download mp3 from youtube including embedded thumbnails



echo -e "\e[32m Youtube to mp3 HQ\e[0m \e[39m"
echo -e " Downloading.."
youtube-dl --prefer-ffmpeg --extract-audio --audio-format mp3 --audio-quality 0 -o ~/mp3/'%(title)s.%(ext)s' --embed-thumbnail $1 
echo -e "Done"
